version: "3"

services:

  db:
    ports:
    - ${LOCAL_DB_PORT}:5432
    volumes:
    - pgdata:${PGDATA}

  migration:
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile

  service:
    build:
      args:       { PACKAGE: "${PACKAGE}" }
      context:    ../../../.
      dockerfile: ./env/docker/service/Dockerfile
    ports:
    - ${LOCAL_SERVICE_HTTP_PORT}:8080
    - ${LOCAL_SERVICE_PROFILING_PORT}:8090
    - ${LOCAL_SERVICE_MONITORING_PORT}:8091
    volumes:
    - vendor:/usr/share/passport

  server:
    entrypoint: |
      /bin/sh -c "echo $$BASIC_USER:`(echo $$BASIC_PASS | openssl passwd -crypt -stdin -noverify)` >> /etc/nginx/.htpasswd \
                  && /entrypoint.sh"
    ports:
    - ${LOCAL_SERVER_HTTP_PORT}:80
    - ${LOCAL_SERVER_HTTPS_PORT}:443
    volumes:
    - certificates:/etc/nginx/ssl
    - letsencrypt:/etc/letsencrypt
    - vendor:/usr/share/nginx/html/vendor

volumes:

  pgdata:       { driver: local }

  certificates: { driver: local }
  letsencrypt:  { driver: local }

  vendor:       { driver: local }
