version: "3"

services:
  server: # https://hub.docker.com/r/kamilsk/nginx/
    image: nginx:mainline # todo replace it when https://github.com/kamilsk/shared/issues/342 will be ready
    depends_on:
    - service
    entrypoint: |
      /bin/sh -c "envsubst '$$SERVICE_HOST $$SITE_PORT $$API_PORT $$SITE_HOSTNAME $$API_HOSTNAME' \
                  < /etc/nginx/conf.d/server.template > /etc/nginx/conf.d/server.conf \
                  && nginx -g 'daemon off;'"
    env_file: .env
    ports:
    - 80:80
    volumes:
    - ./server.conf:/etc/nginx/conf.d/server.template:ro
    - certificates:/etc/nginx/ssl
    - le_challenge:/usr/share/sites/${SITE_HOSTNAME}

  service: # https://hub.docker.com/_/golang/
    image: golang:1.10
    command: [
      "go", "run", "--tags=demo-cross-origin", "env/cross-origin/server.go",
      "--api-host=${API_HOSTNAME}", "--api-port=${API_PORT}",
      "--site-host=${SITE_HOSTNAME}", "--site-port=${SITE_PORT}",
    ]
    env_file: .env
    volumes:
    - ../../:/go/src/github.com/kamilsk/passport
    working_dir: /go/src/github.com/kamilsk/passport

volumes:
  certificates:
    driver: local

  le_challenge:
    driver: local
