language: go

go:
- master
- 1.x
- 1.9.x
- 1.10.x
- 1.11.x

matrix:
  fast_finish: true

sudo: false

script:
- make test ARGS='-timeout=1s'

env:
- META=github.com/kamilsk/passport/pkg/cmd

after_success:
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.10* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/73f5dfca113f6d94f560
    on_success: change
    on_failure: always
    on_start:   never
