version: "3"

services:
  db: # https://hub.docker.com/_/postgres/
    image: postgres:10-alpine
    env_file: .env
    ports:
    - 5432:5432
    restart: always
    volumes:
    - pgdata:${PGDATA}

  server: # https://hub.docker.com/r/kamilsk/nginx/
    image: kamilsk/nginx:alpine
    entrypoint: |
      /bin/sh -c "envsubst '$$SERVICE_HOST $$SERVICE_PORT $$DOMAIN_NAME $$DOMAIN_PORT' \
                  < /etc/nginx/conf.d/service.template > /etc/nginx/conf.d/service.conf \
                  && echo $$BASIC_USER:`(echo $$BASIC_PASS | openssl passwd -crypt -stdin -noverify)` >> /etc/nginx/.htpasswd \
                  && /entrypoint.sh"
    env_file: .env
    ports:
    - 8080:${DOMAIN_PORT}
    restart: always
    volumes:
    - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/service.conf:/etc/nginx/conf.d/service.template:ro
    - certificates:/etc/nginx/ssl
    - le_challenge:/usr/share/sites/${DOMAIN_NAME}

volumes:
  pgdata:
    driver: local

  certificates:
    driver: local

  le_challenge:
    driver: local
